Comparison lemma for distributive lattice
agda/cubical pull request #1013
Opened 2023-06-20 07:34 UTC by mzeuner

If `B` is a basis of a distributive lattice `L`, then the categories of sheaves on `B` and sheaves on `L` are equivalent.

2023-06-20 07:44 UTC, mortberg requested changes
Very nice! Just a few comments about naming and a reference

2023-06-20 07:44 UTC, mortberg commented on Cubical/Categories/DistLatticeSheaf/ComparisonLemma.agda
> +   -- isSheafGi = restPresSheafProp G isSheafG
commented code

2023-06-20 07:44 UTC, mortberg commented on Cubical/Categories/DistLatticeSheaf/ComparisonLemma.agda
> + extSh : Functor ShB ShL
Maybe expand "Sh" to "Sheaf"? Probably applies to other names as well. This will be more consistent with the naming we have for "Presheaf"

2023-06-20 07:44 UTC, mortberg commented on Cubical/Categories/DistLatticeSheaf/ComparisonLemma.agda
> +{-# OPTIONS --safe --lossy-unification #-}
Add a reference to https://ncatlab.org/nlab/show/comparison+lemma or similar to explain the name a bit?

2023-06-21 09:46 UTC, mzeuner commented
Implemented all the requested changes from @mortberg . The notation should be more consistent now. 
Anything else that should be fixed/changed?

2023-06-29 16:50 UTC, mortberg approved these changes

2023-06-29 16:51 UTC, mortberg commented
Looks good to me! Merging

2023-06-29 16:51 UTC, merged