Some miscellaneous separated/stable type facts
agda/cubical pull request #1030
Opened 2023-08-09 00:21 UTC by dolio

Added separatedness of `Bool`

Added some convenient functions for deriving `Stable` and `Separated` for e.g. functions.

These were some general facts I found useful while working on some other stuff, sort of similar to various h-level combinators.

2023-09-01 14:05 UTC, MatthiasHu requested changes
Nice contribution!
I have some remarks, I hope they are not too annoying. :-)

2023-09-02 17:56 UTC, dolio commented on Cubical/Relation/Nullary/Properties.agda
> +Stable× : Stable A -> Stable B -> Stable (Σ A (λ _ → B))
I see. I didn't realize the `.Base` module exported `_×_`.

2023-09-02 19:26 UTC, dolio commented on Cubical/Relation/Nullary/Properties.agda
> +Stable→ Bs e x = Bs λ k → e λ f → k (f x)
I think I just proved the `→` versions first, before I was sure that the `Π` version would work.

2023-09-04 16:17 UTC, MatthiasHu approved these changes

2023-09-04 16:23 UTC, MatthiasHu commented
I will merge this when the CI is done.

2023-09-04 16:38 UTC, merged