CW complexes, cellular homology + a lot more
agda/cubical pull request #1111
Opened 2024-03-03 23:57 UTC by aljungstrom

Here's a big one... This is a bunch of code primarily written by @loic-p and me about CW complexes and cellular homology. It's part of a bigger project with @mortberg and was previously in a private repo. I guess Anders should be reviewing this one. It contains:

1. Definitions of CW complexes, (finite) cellular maps and (finite) cellular homotopies. This includes things like (constructive versions of) the cellular approximation theorems. All of this can be found under `Cubical.CW`.
2. Chain complexes, chain homotopies and related constructions. We use finite counterparts of many of these constructions to keep things constructive.
3. Construction of the chain complex associated to a CW complex à la Buchholtz and Favonia. This includes a bunch of proofs concerning properties of the degree of (1) maps between spheres (2) maps between bouquets of spheres.
4. Perhaps **most importantly**: cellular homology and, in particular, its functoriality. Actually, this is concerns two homology theories: we first construct `Hˢᵏᵉˡ` which defines the homology of an explicitly given skeleton and then lift this to  `Hᶜʷ`, the homology of an arbitrary CW complex, i.e. a type which is merely equivalent to the colimit of some skeleton.  We have been careful to set things up so that it works for possibly infinite dimensional CW complexes and not just finite ones. You can find the main results in `Cubical.CW.Homology`

FYI, I also introduced a new definition of _<_ on the naturals and used a definition of Fin n in terms of it. I would suggest we use this as the primary definition of Fin n in the future as the original one caused several of the proofs in this PR to be ~3 times as long (transport hell). But let's leave that to a future discussion...

2024-03-03 23:58 UTC, aljungstrom commented
@rwbarton @owen-fool maybe this is of interest to your formalisation project?

2024-03-10 22:15 UTC, rwbarton commented
Nice! I saw your HoTT/UF abstract a couple weeks ago. I find it a bit surprising that it's possible to do cellular homology synthetically like this without having a homotopy-invariant homology theory first; I'll have to look into exactly how it works.

Of course, my burning question is: any prospects for proving the Hurewicz theorem for simply-connected finite CW complexes, in terms of this cellular homology?

2024-03-13 17:03 UTC, aljungstrom commented
@rwbarton  We're hoping it should be easier but no promises yet. On the blackboard it felt like it should follow pretty easily given the appropriate theory about n-connected complexes. I'll get back to you if I make any progress.

2024-04-12 14:25 UTC, mortberg requested changes
Cool stuff! Some minor comments

2024-04-12 14:25 UTC, mortberg commented on Cubical/CW/Approximation.agda
> +-- a finite cellular homotopies relative
?

2024-04-12 14:25 UTC, mortberg commented on Cubical/CW/Approximation.agda
> +  → (record { fmap = fst ∘ g ; fcomm = λ r x → sym (hom r x) })
copattern-match?

2024-04-12 14:25 UTC, mortberg commented on Cubical/CW/Approximation.agda
> +  → (record { fmap = fst ∘ g ; fcomm = λ r x → sym (hom r x) })
Constructor?

2024-04-12 14:25 UTC, mortberg commented on Cubical/CW/Approximation.agda
> +    ∣ (record { fhom = λ {(zero , p) x → ⊥.rec (CW₀-empty C x)}
record..

2024-04-12 14:25 UTC, mortberg commented on Cubical/CW/Approximation.agda
> +    ∣ (record { fhom = λ {(zero , p) x → ⊥.rec (CW₀-empty C x)}
And more later

2024-04-12 14:25 UTC, mortberg commented on Cubical/CW/Homotopy.agda
> +  -- keeping imports here for now
Move

2024-04-12 14:25 UTC, mortberg commented on Cubical/Data/Fin/Inductive/Base.agda
> +-- inductive definition of <
Move this and related stuff to Nat

2024-04-12 14:25 UTC, mortberg commented on Cubical/Data/Fin/Inductive/Properties.agda
> +open import Cubical.Data.Fin.Base renaming (Fin to Fin*) hiding (¬Fin0)
Separate file?

2024-04-12 14:25 UTC, mortberg commented on Cubical/HITs/SequentialColimit/Base.agda
> +realiseSequenceMap record { map = map ; comm = comm } (incl x) = incl (map _ x)
??

2024-04-12 14:25 UTC, mortberg commented on Cubical/HITs/SequentialColimit/Base.agda
> +realiseSequenceMap record { map = map ; comm = comm } (incl x) = incl (map _ x)
Constructor?

2024-04-12 14:25 UTC, mortberg commented on Cubical/HITs/SequentialColimit/Properties.agda
> +  (record { inclP = λ {k} → paths k
record...

2024-04-12 14:25 UTC, mortberg commented on Cubical/Algebra/CommRing/Localisation/InvertingElements.agda
> +      path = f ^ l · (g ^ l · r · g ^ m) · (1r · f ^ m · 1r)
@mzeuner check this out!

2024-05-06 14:11 UTC, mortberg approved these changes

2024-05-06 14:11 UTC, merged