Determinant and Adjugate Matrix
agda/cubical pull request #1165
Opened 2024-10-30 14:50 UTC by FranziskusWiesnet

In the four new files, the determinant of a matrix over a commutative ring is introduced through Laplace expansion, and it is proven that the adjugate matrix multiplied by the matrix itself equals the determinant times the identity matrix.
Additionally, it is shown that the determinant is independent of the row or column chosen for expansion, along with a few other minor properties of the determinant.
I am happy to consider any improvements.

2024-10-31 11:02 UTC, felixwellen commented on dist-newstyle/cache/compiler
This looks like accidentally committed files

2024-10-31 11:05 UTC, felixwellen commented
Thanks for opening a PR on this! Determinants would certainly be very useful to have.

2024-10-31 11:06 UTC, felixwellen commented on Cubical/Algebra/Determinat/Minor.agda
> +module Minor where
Module names should always be fully qualified, i.e. ```Cubical.Algebra.Determinant.Minor``` in this case.

2024-10-31 12:30 UTC, FranziskusWiesnet commented on dist-newstyle/cache/compiler
Yes. I have removed it.

2025-01-15 04:35 UTC, anshwad10 commented on Cubical/Algebra/Determinat/Base.agda
> +  -- Definition of the minor factor
I noticed that there is some redundancy in the Determinat (is that a typo?) .Base file. `MF i` is just `(- 1r) ^ i` (`_^_` is defined in Cubical.Algebra.CommRing.Properties, and many of the properties of minor factor you prove are already proved there). And `+Compat` can by proved more simply by `cong₂ _+_`.

2026-05-11 08:21 UTC, mortberg commented
What is the state of this PR? Has all comments been addressed so that it's ready for another round of reviews/merging?

2026-05-11 08:26 UTC, felixwellen commented
I honestly don't remember - I think I had a discussion with @FranziskusWiesnet which might not have taken place here. At a quick glance I only see `{-# OPTIONS --safe #-}` which are all not necessary anymore.

2026-05-15 16:13 UTC, FranziskusWiesnet commented
Thanks for checking in! Since this PR has been open for quite some time, I do not remember all details either.
As far as I can see, Felix’s fixes have been merged and the CI currently passes. I can remove the remaining unnecessary {-# OPTIONS --safe #-} pragmas in a small commit. 

Could someone start another round of review? I would be happy to address any remaining issues.

2026-05-18 08:47 UTC, mortberg requested changes
Many thanks! Lots of good stuff! I had some suggestions for improvements and then it can be merged

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +{-# OPTIONS --safe #-}
remove

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +    -- Properties of WeakenFin
Move to theory for Fin

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +    sucPredFin : (k l : Fin (suc (suc n))) → toℕ k <' toℕ l → suc (predFin l) ≡ l
move

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +  strongenFin : {j : Fin (suc n)} → (i : Fin (suc n)) → toℕ i <' toℕ j → Fin n
move

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +  strongenFin : {j : Fin (suc n)} → (i : Fin (suc n)) → toℕ i <' toℕ j → Fin n
with lemmas about it

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +  strongenFin : {j : Fin (suc n)} → (i : Fin (suc n)) → toℕ i <' toℕ j → Fin n
Also, "strongen" should probably be "strengthen"?

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Adjugate.agda
> +  FinCompare : {n : ℕ} → (k l : Fin n) →  (k ≡ l) ⊎ ((toℕ k <' toℕ l) ⊎ (toℕ l <' toℕ k))
move

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Base.agda
> +{-# OPTIONS --safe #-}
remove

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Base.agda
> +  -- Definition of the minor factor
Sounds right. Can you fix?

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Base.agda
> +  weakenweakenFinLe : {n : ℕ} → (i : Fin (suc n)) → (j : Fin (suc n)) → toℕ i ≤' toℕ j → weakenFin i ≤'Fin weakenFin j
move

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Base.agda
> +    weakenFinLe : {n : ℕ} → (i : Fin (suc (suc n))) → (j : Fin (suc n)) → toℕ i ≤' toℕ j → i ≤'Fin weakenFin j
move

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Minor.agda
> +{-# OPTIONS --safe #-}
remove

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Minor.agda
> +  remove-column : {A : Type ℓ} {n m : ℕ} (j : Fin (suc m)) (M : FinMatrix A n (suc m)) → FinMatrix A n m
Rename to removeCol

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Minor.agda
> +  remove-row : {A : Type ℓ} {n m : ℕ} (i : Fin (suc n)) (M : FinMatrix A (suc n) m) → FinMatrix A n m
Rename to removeRow

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/Minor.agda
> +  remove-column-row-comm : {A : Type ℓ} {n m : ℕ}  (i : Fin (suc n)) (j : Fin (suc m)) (M : FinMatrix A (suc n) (suc m)) (k : Fin n) (l : Fin m) →  (remove-row i (remove-column j M)) k l ≡  (remove-c
Long line. There are other examples in this file as well

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/RingSum.agda
> +{-# OPTIONS --cubical #-}
remove

2026-05-18 08:47 UTC, mortberg commented on Cubical/Algebra/Determinat/RingSum.agda
> +{-# OPTIONS --safe #-}
remove

2026-08-18 15:34 UTC, FranziskusWiesnet commented
Thank you for the review. I have now addressed the review comments and updated the branch to the current master.
The files I modified as part of the determinant development and review fixes are:

- The four files in Cubical/Algebra/Determinat/
- Cubical/Data/FinData/Properties.agda
- Cubical/Data/FinData/Order.agda

Since I based the revised version on the current upstream master, the PR also contains many unrelated changes that have been added to master since the original submission.

2026-08-19 05:26 UTC, mortberg commented
I think this is ready to be merged now, except for one typo: The directory should be `Algebra/Determinant` not `Algebra/Determinat` (note the missing `n`)

2026-08-19 15:46 UTC, FranziskusWiesnet commented
Thank you! The typo is fixed.

2026-08-20 05:10 UTC, mortberg commented
Perfect! Will merge once the CI is finished

2026-08-20 05:28 UTC, merged