Some work related to countable types
agda/cubical pull request #514
Opened 2021-02-21 21:00 UTC by dolio

This PR contains an assortment of stuff written working up to definitions of countability and similar properties.

Miscellaneous convenience stuff:
- Discreteness can be translated through a section
- `isSet` for plain functions when the codomain is a set
- `isPropDep` alias
- Generalized the type of `PropositionalTruncation.rec2`

More properties of the recursively defined ordering on the natural numbers, including well-foundedness.

Define various omniscience principles in `Cubical.Axiom.Omniscience`, along with how they imply one another.

Gives some more specific facts about omniscience on the naturals (could probably be generalized to any well-founded total ordering).

Define some additional structure on the `Conat` type, including the type of natural numbers bounded by a conat, which is analogous to `Fin`. Prove that this is similarly injective.

Show that an injective function from `Conat` to `ℕ` implies the weak limited principle of omniscience on the naturals. Show that a certain pseudo 'covering' function from `ℕ` to `Conat` being an equivalence implies the limited principle of omniscience.

Define various notions of countability, their interaction, and displayed versions:
- Denumerability for being merely equivalent to `ℕ`
- Countability for being equivalent to a set with a `Conat` size
- CountableIndexability for admitting a surjective 'partial' function from the naturals
These are analogous to notions of being finite.

2021-02-21 21:01 UTC, dolio commented
There seems to be an issue where the `Everything` file generation doesn't include `--guardedness` for files that transitively import files that use it, causing tests to fail. Not certain what to do about that.

2021-02-26 03:54 UTC, dolio commented
I hit more snags than I expected, but I was able to reprove the countability stuff for detachable lower segments of ℕ, so I switched to that, since it seems like less of a hassle tooling wise.

2021-03-02 09:43 UTC, Saizan commented
Any idea what's going wrong with the test?

2021-03-02 16:19 UTC, dolio commented
I think it's just complaining that some modules are not transitively imported by `Everything` modules because I switched the basis for countability away from coinduction. Sorry about the delay fixing it. I can't easily see the issue locally, because for some reason my local agda version instead reports a ton of unsolved metas in `ZCohomology`.

2021-03-02 16:24 UTC, ecavallo commented
Could the unsolved metas be related to #508? In that case merging from master should take care of them.

2021-03-02 17:43 UTC, dolio commented
Oh, possibly. I guess my branch is kind of behind. Thanks for the tip.

2021-03-03 03:50 UTC, dolio commented
Okay, I'm not quite sure what the problem is now. It seems to be in a module I didn't modify, and it also doesn't happen to me locally. Possibly it's specific to the version of Agda used?

2021-03-05 14:49 UTC, ecavallo commented
Yes, another problem due to changes in a new version of Agda. I fixed this in #518, so merge from master again :sweat_smile:

2021-03-18 19:01 UTC, ecavallo requested changes
Looking good! I have a few requests and suggestions before we merge.

2021-03-20 14:15 UTC, dolio commented on Cubical/Axiom/Omniscience.agda
> +LLPO' : Type ℓ → Type ℓ
Sure, I can go with that. Although it's never more than a set.

2021-03-20 14:20 UTC, dolio commented on Cubical/Data/Bool/Properties.agda
> +_ ≥ _ = Unit
This one is due to the exact behavior of reductions being important to the simplicity of other proofs. Just using `c ≤ b` gets different judgmental equality.

2021-03-20 14:22 UTC, dolio commented on Cubical/Data/Nat/Lower.agda
> +... | false | [ p ]ᵢ = mzv λ i k → mz-lemma f mf p k i
Okay, sure. I guess I was eagerly avoiding indexed types due to them (currently) getting stuck on some cubical stuff, but it probably doesn't matter in this example.

2021-03-20 14:28 UTC, dolio commented on Cubical/Displayed/Countable.agda
> +Denumeration : Type ℓ → Type ℓ
I'm fine to move them. I guess I was thinking forward to synthetic computability axioms, like, 'the countably enumerable subsets of ℕ are countably enumerable,' and thinking the 'structure' bits might be used for that. But I wasn't super convinced of their utility myself, really.

2021-03-22 13:20 UTC, ecavallo commented on Cubical/Data/Bool/Properties.agda
> +_ ≥ _ = Unit
Oh, that makes sense.

2022-05-03 11:06 UTC, merged