General Eilenberg-MacLane spaces (+ some theory)
agda/cubical pull request #597
Opened 2021-08-20 12:40 UTC by aljungstrom

This PR contains a bunch of generalisation of the stuff in ZCohomology to general Eilenberg-MacLane spaces, K(G,n). There's not that much new really -- all proofs go through in an almost identical manner. There's some stuff left to translate, but it was probably time for a PR... 

Here's some of the stuff
- A construction of the tensor product of abelian groups and a proof that it has the universal property. There's commutativity and associativity of tensor products.
- General Eilenberg-MacLane spaces, K(G,n). 
- A direct proof of the "wedge connectivity lemma" for these spaces.
- The "group structure" on K(G,n).
- A proof that `Ω K(G,n+1) ≃ K(G,n)` (for n > 0 -- the case n = 0 was already done by @felixwellen)
- The cup product, defined as a function `K(G,n) → K(H,m) → K(G ⊗ H , (n + m))`. I'll wait with the non tensor version.
- Left and right distributivity of the cup product. I'll do associativity and graded commutativity later.
- A version of `→∙Homogeneous≡` for constructing squares in `A →∙ B`

2021-08-20 20:55 UTC, felixwellen commented
Very nice! The proof you mentioned was actually done by Ulrik, though....
Are the coefficients constant everywhere? I think it would be a good idea to use dependent coefficients whenever possible. And it is probably a good time to rename 'ZCohomology' to 'Cohomology'. But I guess both can be treated as separate issues.

2021-11-02 15:17 UTC, aljungstrom commented
> Very nice! The proof you mentioned was actually done by Ulrik, though.... Are the coefficients constant everywhere? I think it would be a good idea to use dependent coefficients whenever possible. And it is probably a good time to rename 'ZCohomology' to 'Cohomology'. But I guess both can be treated as separate issues.

Damn sorry, I kind of forgot about this PR. Do you remember what you meant by this? I'm a bit uncertain about what dependent coefficients could mean in this context.

2021-11-02 15:21 UTC, felixwellen commented
I'll write an issue.

2021-12-15 12:03 UTC, ecavallo commented
I'm going to review this, but could you merge from master first? I suspect some things are out of date by now.

2022-01-03 14:27 UTC, ecavallo commented
Looks like there's some conflict where `isGroupHomInv` is now defined in multiple places.

2022-01-09 23:32 UTC, aljungstrom commented
Sorry, should be ok now

2022-02-08 12:00 UTC, ecavallo requested changes
Have some mainly minor suggestions. I tried to figure out some bigger simplifications but ended up in over my head, haha...

2022-02-08 12:59 UTC, aljungstrom commented on Cubical/Algebra/Group/EilenbergMacLane/GroupStructure.agda
> +    lol g h = compPath-filler (emloop g) (emloop h) ▷ sym (emloop-comp _ g h)
lol

2022-02-08 12:59 UTC, aljungstrom commented
Thanks for the review, and sorry I have been so slow with this. I'll clean this up as soon as this whole pi4s3 business is over.

2022-02-08 13:03 UTC, ecavallo commented
No problem, I was not fast reviewing it either!

2022-05-02 15:37 UTC, aljungstrom commented on Cubical/Algebra/Group/EilenbergMacLane/GroupStructure.agda
> +  renaming (elim to trElim ; rec to trRec ; rec2 to trRec2)
never

2022-05-02 15:49 UTC, aljungstrom commented
FIXED!

░░░░░░░░░░░░░░░░░░░░░░█████████░░░░░░░░░
░░███████░░░░░░░░░░███▒▒▒▒▒▒▒▒███░░░░░░░
░░█▒▒▒▒▒▒█░░░░░░░███▒▒▒▒▒▒▒▒▒▒▒▒▒███░░░░
░░░█▒▒▒▒▒▒█░░░░██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██░░
░░░░█▒▒▒▒▒█░░░██▒▒▒▒▒██▒▒▒▒▒▒██▒▒▒▒▒███░
░░░░░█▒▒▒█░░░█▒▒▒▒▒▒████▒▒▒▒████▒▒▒▒▒▒██
░░░█████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██
░░░█▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒██
░██▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒██▒▒▒▒▒▒▒▒▒▒██▒▒▒▒██
██▒▒▒███████████▒▒▒▒▒██▒▒▒▒▒▒▒▒██▒▒▒▒▒██
█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒████████▒▒▒▒▒▒▒██
██▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██░
░█▒▒▒███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██░░░
░██▒▒▒▒▒▒▒▒▒▒████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█░░░░░
░░████████████░░░█████████████████░░░░░░

2022-05-03 08:49 UTC, ecavallo approved these changes
fine

2022-05-03 08:49 UTC, merged