rotation of Square (by 90deg)
agda/cubical pull request #600
Opened 2021-08-24 19:49 UTC by marcinjangrzybowski

I am not sure where would be a good place for lemma like this, 
maybe  /Foundations/Square/Properties.agda ?
for now, the code is in Experiments.

```
  Equivalence of rotating the Square by 90deg can be easily constructed in two ways:

    - from isomorphism of switching dimensions  (sq i j ⇄ sq (~ j) i)
    - from path obtained via applying Square to 4 paths

  This module shows that those equivalences are equal.
```

2022-03-16 08:25 UTC, marcinjangrzybowski commented
> let's put it in `Foundations.Path` for now and we can deal with the reorganization question in a future PR.

@ecavallo I moved the definition as requested, sorry for the late answer :)

2022-05-02 14:44 UTC, mortberg requested changes

2022-05-02 14:44 UTC, mortberg commented on Cubical/Foundations/Path.agda
> +              (λ _ → coe0→i (λ i' → ≡rotateSquare i') l x i j)
Can't you just use a transpFill here and get rid of the dependency on CartesianKanOps?

2022-05-02 15:14 UTC, mortberg commented
Actually, do you have some use case for this?

2022-05-03 13:50 UTC, mortberg commented
Now this has a conflict so I'll close it for now. Feel free to re-open if you fix the conflict and have a use case for the proof! I'm somewhat reluctant to add things that are not of very general interest to the Foundations, so it should probably go somewhere else no matter what

2022-05-03 13:50 UTC, closed without merging