Add Hom as instance of AbGroup
agda/cubical pull request #635
Opened 2021-11-21 13:38 UTC by barrettj12

2021-11-28 11:46 UTC, barrettj12 commented
@mortberg I thought `HomAbStr` was a better name than `HomIsAb`, thoughts?

2021-12-15 09:50 UTC, mortberg requested changes
I would call it `HomAbGroupStr`. Apart from this and a comment this looks good to me

2021-12-15 09:50 UTC, mortberg commented on Cubical/Algebra/AbGroup/Instances/Hom.agda
> +HomAbStr A B = abgroupstr
Please define using copatterns (I think `makeIsAbGroup` can still be used here, so only the top-level need copatterns)

2021-12-15 15:24 UTC, mortberg approved these changes

2021-12-15 15:24 UTC, merged