Examples of finite presentations of CommAlgebra's
agda/cubical pull request #680
Opened 2021-12-17 17:08 UTC by felixwellen

The goal of this PR is, to introduce the notion of a finite presentation (instead of just the Prop 'finitelyPresented') and construct some basic finite presentations.
However, I'm stuck here because of a type checking speed issue. It seems that plugging the algebra ``makeFPAlgebra n relations`` into ``CommAlgebraEquiv`` is the cause of the slowdown. Maybe because the fields of this more complicated CommAlgebra get expanded? I don't know...

2022-01-04 16:02 UTC, mortberg commented
Strange... I have no good idea why it's so slow. Did you try making some parts abstract in order to isolate where the slowness is coming from?

2022-01-04 16:12 UTC, felixwellen commented
I'm not sure if I tried that.
My guess is, that it could be lots of work to actually expand all the fields of 'makeFPAlgebra ...'.

2022-01-04 16:18 UTC, felixwellen commented
Hm. Now it seems to be a lot faster with an abstract 'makeFPAlgebra'... Thanks!

2022-01-09 14:17 UTC, felixwellen commented
Now I have a new, very much related tc-speed problem. The 'abstract' term I defined is not really usable in the way I want without introducing the same speed problem again...

2022-05-03 09:41 UTC, mortberg requested changes
small comments

2022-05-03 09:41 UTC, mortberg commented on Cubical/Algebra/CommAlgebra/Properties.agda
> +    ℓ ℓ′ ℓ″ ℓ‴ ℓ' ℓ'' ℓ''' : Level
Bad levels?

2022-05-03 09:41 UTC, mortberg commented on Cubical/Algebra/CommAlgebra/FGIdeal.agda
>  open import Cubical.Foundations.Prelude
empty line

2022-05-03 13:33 UTC, merged