Polynomials over commutative rings added
agda/cubical pull request #714
Opened 2022-02-04 13:32 UTC by AkermanRydbeck

Hello,

Here is an implementation of polynomials over commutative rings.

Cheers,
Carl

2022-02-07 09:59 UTC, mortberg requested changes
Tack så mycket!

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/CommRing/Instances/Polynomials.agda
> +ℙ : (R : CommRing ℓ) → CommRing ℓ
Bättre namn, typ `Poly`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/CommRing/Instances/Polynomials.agda
> +ℙ : (R : CommRing ℓ) → CommRing ℓ
Typen kan vara ` CommRing ℓ → CommRing ℓ`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/CommRing/Instances/Polynomials.agda
> +      CommRingStr.0r str = PolyMod.0P R
Testa att ta bort ` CommRingStr.`, funkar det inte ändra till `open CommRingStr` ovan (så inget `(snd R)`)

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +-- A polynomial a₁ +  a₂x + ... + aⱼxʲ of order j is represented as a list [a₁, a₂, ...,aⱼ]
order <- degree

och ett polynom är en lista "modulo trailing zeros"

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +                          (Bset : isSet B) where
Indentering

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +-- A polynomial a₀ +  a₁x + ... + aⱼxʲ of order j is represented as a function f
degree

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  IsSetPolyFun : isSet PolyFun
`isSetPolyFun`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  IsZero : ℕ → Bool
Flytta till `Cubical.Data.Nat.Base` och byt namn till `isZero`   (om det blir konflikter pga import av Bool där så får vi ser vad vi gör)

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +    help : (p : ℕ → R) (n : ℕ) → ((m : ℕ) → n ≤ m → p m ≡ 0r) → Poly
Byt namn till `rem1`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +    bar : (f : ℕ → R) (n : ℕ) → (h : (m : ℕ) → n ≤ m → f m ≡ 0r) (m : ℕ) →
Byt namn till `rem2`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  lemmaisSet : (p : Poly) → PolyFun→Poly (Poly→PolyFun p) ≡ p
Byt namn till `PolyFun→Poly→PolyFun`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  IsSetPoly : isSet Poly
Byt namn `isSetPoly`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +                           (λ p → lemmaisSet p)
Behövs inget lambda här, utan `lemmaIsSet` räcker (eller `PolyFun→Poly→PolyFun` när du bytt namn då)

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  PolyIsSet : isSet Poly
Kan tas bort, använd `isSetPoly` överallt istället

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  ReplicatePoly : (n : ℕ)  → Poly
Byt namn till `replicatePoly0`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  ReplicatedZeros=[] : ∀ (n : ℕ) → ReplicatePoly n ≡ 0P
`replicatePoly0Is0P`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  Poly-Poly-P=P : (p : Poly) → Poly- (Poly- p) ≡ p
`Poly-Poly-`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +                             (refl)
parenteser behövs inte runt refl

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +  Poly+Rid = λ p → refl
`Poly+Rid p = refl`

2022-02-07 09:59 UTC, mortberg commented on Cubical/Algebra/Polynomials.agda
> +-- Main Theorem                  --
Ta bort `PolyCommRing` här och referera till `Cubical.Algebra.CommRing.Instances.Polynomials` i en kommentar

2022-03-08 13:34 UTC, mortberg approved these changes

2022-03-08 17:06 UTC, mortberg commented
Oops, there is a clash for `isZero`: https://github.com/agda/cubical/runs/5465312974?check_suite_focus=true

2022-03-09 16:41 UTC, felixwellen commented
And I am really happy we have this definition of polynomials now! And also that it is a set - I didn't know that it works this nicely.

2022-03-10 10:26 UTC, mortberg commented
> You can just hide `isZero` on import in `HornerForms.agda`, then everything type checks.

Yes, that should be the best solution. @AkermanRydbeck  Can you do it please?

2022-03-10 10:27 UTC, mortberg commented
> And I am really happy we have this definition of polynomials now! And also that it is a set - I didn't know that it works this nicely.

Yes, I'm also very pleased that we managed to prove that it's a set without truncating. It's very nice to not have to deal with the truncation and to be able to eliminate into arbitrary types.

2022-03-10 11:57 UTC, AkermanRydbeck commented
Hello, glad you like it Felix. 

isZero is hidden now.

/Carl

2022-03-10 13:51 UTC, merged