James Construction (Connectivity)
agda/cubical pull request #729
Opened 2022-02-25 03:42 UTC by kangrongji

This PR contains the connectivity results of James construction. It also contains necessary facts about direct colimits and pushout-product. I think the general theory of James has been fully formalized. @aljungstrom @mortberg

2022-02-25 07:55 UTC, mortberg commented
Very nice! It would be very interesting to see if we can use this to get the more general result in Guillaume's thesis formalized... @aljungstrom  What do you think?

(As you might have noticed I've been very quiet here lately. I'm extremely busy with teaching at the moment and will be for a few more weeks, so won't have time to review any PRs for a while longer).

2022-02-26 13:21 UTC, kangrongji commented
I hope this could be help:)

2022-03-01 14:03 UTC, aljungstrom commented
Very nice! @mortberg I don't think the more general statement in Brunerie's thesis is that interesting (I think we get the remaining homotopy groups by Freudenthal). But there's definitely more stuff we can explore now that we have James!

2022-03-26 11:01 UTC, kangrongji commented
Any update on your "general result"? @aljungstrom

2022-03-28 20:39 UTC, aljungstrom commented
> Any update on your "general result"? @aljungstrom

Oh no unfortunately I had nothing great in mind. I just confused Anders' question with another one we had discussed earlier that day (which was nothing too exciting - just an application of Freudenthal).

2022-05-03 11:13 UTC, ecavallo commented
What are the dependencies between the James PRs? Should we merge #718 and #722 before this one?

2022-05-03 12:01 UTC, kangrongji commented
> What are the dependencies between the James PRs? Should we merge #718 and #722 before this one?

Yes, each one depends on the previous one.

2022-05-09 14:59 UTC, ecavallo requested changes
Just a superficial request: I want to always use `isConnected[...]` in names of connectedness theorems. (But it's fine if this isn't followed in private definitions.)

Nice idea to introduce a shifted elimination principle for the sequential colimit. I had so much trouble with associativity trying to prove things about these a long time ago...

2022-05-09 14:59 UTC, ecavallo commented on Cubical/HITs/SequentialColimit/Properties.agda
> +    isConnInl∞ : isConnectedFun d (inl∞ n)
isConn -> isConnected

2022-05-09 14:59 UTC, ecavallo commented on Cubical/HITs/James/Inductive/PushoutFormula.agda
> +  isConnInl n conn m = isConnInl∞ _ _ _ (isConnIncl>n _ conn _)
isConn -> isConnected

2022-05-10 01:54 UTC, kangrongji commented on Cubical/HITs/Pushout/PushoutProduct.agda
> +isConn×̂ : {m n : ℕ}{f : A → B}{g : X → Y}
done

2022-05-10 01:54 UTC, kangrongji commented on Cubical/HITs/SequentialColimit/Properties.agda
> +    isConnInl∞ : isConnectedFun d (inl∞ n)
done

2022-05-10 01:54 UTC, kangrongji commented on Cubical/HITs/James/Inductive/PushoutFormula.agda
> +  isConnInl n conn m = isConnInl∞ _ _ _ (isConnIncl>n _ conn _)
done

2022-05-10 01:56 UTC, kangrongji commented on Cubical/HITs/James/Inductive.agda
> +    inclConn = isConnIncl X∙ d conn
done

2022-05-10 02:04 UTC, kangrongji commented
Yup, those who parametrized over natural numbers are just painful and messy.

Btw, I haven't noticed but after you guys clean up all the PRs I realize there has been a WIP on direct limit #592 . It seems the only hole left there is just the shifted eliminators I show here. So it'd better ping @felixwellen .

2022-05-10 04:49 UTC, ecavallo approved these changes
Thanks!

2022-05-10 04:50 UTC, merged