Isomorphisms between hSets, isUnivalent SET
agda/cubical pull request #734
Opened 2022-03-16 08:16 UTC by marcinjangrzybowski

2022-04-04 06:16 UTC, mortberg requested changes
Two small changes requested, then I would be happy to merge!

2022-04-04 06:16 UTC, mortberg commented on Cubical/Categories/Functor/Properties.agda
> +isSet-Functor : isSet (D .ob) → isSet (Functor C D)
I would call this `isSetFunctor`

2022-04-04 06:16 UTC, mortberg commented on Cubical/Foundations/Equiv/Properties.agda
> +  precomposesToId→Equiv f _  (cong fst (invEquiv-is-linv (_ , f∘gIsEquiv))) (snd (compEquiv (invEquiv (_ , f∘gIsEquiv) ) (_ , gIsEquiv)))
Long line

2022-04-04 06:16 UTC, marcinjangrzybowski commented
just saw bunch of similar things merged from one of the previous PRs, I will check if this still anything new in this PR

2022-04-04 06:21 UTC, mortberg commented
> just saw bunch of similar things merged from one of the previous PRs, I will check if this still anything new in this PR

Ok, I looked as well but didn't find anything. But I could possibly have missed something

2022-04-04 06:27 UTC, marcinjangrzybowski commented
Ok, I thought is saw some overlap with `CommRing category is univalent and complete #694`, but I think I was mistaken.

2022-04-04 06:33 UTC, mortberg commented
> Ok, I thought is saw some overlap with `CommRing category is univalent and complete #694`, but I think I was mistaken.

Yes, I thought so too because I could not remember what I had done in that PR... But I think it's all fine and there's no overlap

2022-04-08 14:10 UTC, marcinjangrzybowski commented on Cubical/Foundations/Equiv/Properties.agda
> +  precomposesToId→Equiv f _  (cong fst (invEquiv-is-linv (_ , f∘gIsEquiv))) (snd (compEquiv (invEquiv (_ , f∘gIsEquiv) ) (_ , gIsEquiv)))
done

2022-04-09 10:11 UTC, merged