Adding Nth-polynomials
agda/cubical pull request #740
Opened 2022-03-23 16:29 UTC by thomas-lamiaux

Adding nth-polynomials using a new definition

2022-03-23 23:11 UTC, felixwellen commented
Interesting! Did you see Cubical/Algebra/CommAlgebra/Instances/FreeCommAlgebra.agda?
I think that is related to what you do. It seems you are a bit more economical with the constructors of your type of polynomials.

Btw: You can mark your pull-request as 'draft'. This is a good way to indicate, that it is work in progress.

2022-03-24 03:24 UTC, thomas-lamiaux commented
> Interesting! Did you see Cubical/Algebra/CommAlgebra/Instances/FreeCommAlgebra.agda? I think that is related to what you do. It seems you are a bit more economical with the constructors of your type of polynomials.
 
I didn't see it even though I am currently working with Anders, I think that they originated very differently.
Basically we were looking for a good definition of the direct-sum. Working with one we've come up with, I have realized that I could define nth-polynomials easily and it would simplify some latter proof. 

Plus, I am not a big fan of the current one based on the :: operation. I prefer this one base on "vectorial space". With the difference that the action on the basis is internalized - which comes from the direct sum that is dependent - and seems to facilitate definition and proofs. 
Indeed basically it suffices to specify the behavior for aX^n, to define functions such as the product so all structures rises and that simplify the structure.
 
> Btw: You can mark your pull-request as 'draft'. This is a good way to indicate, that it is work in progress.

Indeed I forgot to do it, it's done thanks

2022-03-29 21:54 UTC, thomas-lamiaux commented
Would adding a syntactic sugar like X^n1...X^nk for base [n1, ... nk] 1 be interesting ? 

(I don't really know how to do so for any k)

2022-03-30 12:43 UTC, mortberg requested changes
Also please remove trailing whitespace

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Base.agda
> +open import Cubical.Foundations.Everything
Don't import Everything

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Base.agda
> +  l l' : Level
\ell

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/CommRing-Structure.agda
> +                       (λ PS QS → PS Poly+ QS)
Poly+

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/CommRing-Structure.agda
> +  is-set (isSemigroup (isMonoid (isGroup (IsRing.+IsAbGroup (IsCommRing.isRing (isCommRing (snd PolyCommRing))))))) = trunc
Use makeIsCommRing

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/CommRing/Instances/Polynomials.agda
> +open import Cubical.Algebra.Polynomials.Polynomials
Rename to `Univariate`

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Base.agda
> +module Cubical.Algebra.Polynomials.Nth-polynomials.Base where
Rename to `Multivariate`

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Poly1-Poly.agda
> +-- lemma translation Xn
Move to properties file for univariate polynomials

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Poly1-Poly.agda
> +-- lemma translation Xn
Also split into base+properties

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/CommRing-Structure.agda
> +module _ (A' : CommRing l) (n : ℕ) where
Move to instantiation to Cubical.Algebra.CommRing.Instances

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/CommRing-Structure.agda
> +module Cubical.Algebra.Polynomials.Nth-polynomials.CommRing-Structure where
Rename to Properties

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Poly0-A.agda
> +  l l' : Level
delete l'

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Comp-Poly.agda
> +  rep-concat : (k l : ℕ) → {B : Type l'} → (b : B) → replicate {_} {k} {B} b ++ replicate {_} {l} {B} b ≡ replicate {_} {k +n l} {B} b
long line

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Comp-Poly.agda
> +  +n-vec-concat : (k l : ℕ) → (v w : Vec ℕ k) → (v' w' : Vec ℕ l) → (v Mr.+n-vec w) ++ (v' Mr.+n-vec w') ≡ (v ++ v') Mr.+n-vec (w ++ w')
long

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Comp-Poly.agda
> +-- Some lemma for the traduction
Move to Vec, maybe generalize?

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Polynomials/Nth-polynomials/Equiv/Induced-Poly.agda
> +lift-poly : (A' B' : CommRing l) → (f : CommRingHom A' B') → (n : ℕ) → CommRingHom (PolyCommRing A' n) (PolyCommRing B' n)
`makeCommRingHomPoly`

also A' and B' can be in different universes?

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Ring/Properties.agda
> +  isRingHomInv : {A' B' : Ring ℓ} → (e : RingEquiv A' B') → IsRingHom (snd B') (invEq (fst e)) (snd A')
Different universes

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/Ring/Properties.agda
> +  invEquivRing : {A B : Ring ℓ} → RingEquiv A B → RingEquiv B A
universes

2022-03-30 12:43 UTC, mortberg commented on Cubical/Algebra/CommRing/Properties.agda
> + invCommRingEquiv : (A B : CommRing ℓ) → CommRingEquiv A B → CommRingEquiv B A
different universes

2022-04-03 11:25 UTC, mortberg commented
There's still some trailing whitespace:

```
~/.cabal/bin/fix-whitespace --check
[ Violation detected ] Cubical/Algebra/Polynomials/Univariate/Properties.agda
```

2022-04-03 15:17 UTC, mortberg approved these changes

2022-04-03 15:17 UTC, merged