CP2
agda/cubical pull request #846
Opened 2022-06-19 21:24 UTC by thomas-lamiaux

@aljungstrom @mortberg this now the one about CP2

2022-07-22 23:36 UTC, thomas-lamiaux commented
@mortberg done

2022-09-18 19:59 UTC, mortberg requested changes
Lots of small comments

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/CP2.agda
> +   -- Nice packging of the cup product
```suggestion
   -- Nice packaging of the cup product
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/CP2.agda
> +  -- Converse Sens on ℤ[X] + ℤ[x]/x
```suggestion
  -- Converse direction on ℤ[X] + ℤ[x]/x
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/CP2.agda
> +               helper = (+PℤIdL _) ∙ cong₂ base (cong (λ X → X ∷ []) (sym (+n-comm k 3))) (sym (·ℤIdR _)) ∙ (sym (+PℤIdR _))
Long line. Could also use `_∙∙_∙∙_`

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/CP2.agda
> +-- Missing lemma that is to be added
I don't understand this comment

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/CupProductProperties.agda
> +
```suggestion
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/S1.agda
> +-- And so kept for pedagogic reasons
```suggestion
-- And so kept for pedagogical reasons
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Sn.agda
> +   This file compute the cohomology Ring of Sn (n ≥ 1)
```suggestion
   This file computes the cohomology ring of Sn (n ≥ 1)
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Sn.agda
> +   to do it for a general n, one need to add a partion.
```suggestion
   to do it for a general n, one needs to add a partition.
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Sn.agda
>    pres·-base-case-int one           a zero          b = cong ℤ[x]→H*-Sⁿ (·PℤComm (base (one ∷ []) a) (base (zero ∷ []) b))
Very long lines around here

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Sn.agda
>             base-case (suc (suc k) ∷ []) a = eq/ 0Pℤ (base (suc (suc k) ∷ []) a)  ∣ ((λ x → base (k ∷ []) (-ℤ a)) , helper) ∣₁
long line

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Unit.agda
> +   This file compute the cohomology ring of the Unit as ℤ[X]/⟨X⟩ and as ℤ.
```suggestion
   This file computes the cohomology ring of Unit as ℤ[X]/⟨X⟩ and as ℤ.
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Unit.agda
> +   - There is oonly one non trivial Cohomology Group.
```suggestion
   - There is only one non trivial cohomology group.
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Unit.agda
> +   - The ismorphism function of H⁰ is simpler so it
```suggestion
   - The isomorphism function for H⁰ is simpler so it
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Unit.agda
> +     makes a some properties definitionally.
```suggestion
     makes some properties definitionally.
```

2022-09-18 19:59 UTC, mortberg commented on Cubical/ZCohomology/CohomologyRings/Unit.agda
> +   Though the file is almost written like Sn excet some simplification.
```suggestion
   Though the file is almost written like Sn except for some simplification.
```

2022-09-19 00:54 UTC, thomas-lamiaux commented
done

2022-09-19 07:27 UTC, merged