Cohomology Ring of RP2 \/ S1
agda/cubical pull request #883
Opened 2022-08-08 02:56 UTC by thomas-lamiaux

Start computing the cohomology Ring of RP2 \/ S1

2022-08-08 02:57 UTC, thomas-lamiaux commented
@aljungstrom is there a reason the name is conntectRP1 and not connectedRP2 ?
https://github.com/agda/cubical/pull/883/files#diff-9c75fc952625dc49a8ecc86762628fb159e048def1b0ba435ca3f13180ce4aceR66

2022-08-08 03:32 UTC, thomas-lamiaux commented
@aljungstrom @mortberg 
As the group are the same and the cup product is supposed to be the same, the proofs of cohomology ring is exactly the same.

As #882 , `phi_1 a cup phi_1 b = 0` doesn't compute, so up to this, we'll have the computation of those rings. 
Axel, could you do look at this when you have sometimes ?

2022-09-05 05:52 UTC, thomas-lamiaux commented
@mortberg  Ready too.

2022-09-19 07:27 UTC, mortberg commented
Lots of conflicts here now, please rebase on master

2022-09-19 13:01 UTC, mortberg requested changes
minor comments

2022-09-19 13:01 UTC, mortberg commented on Cubical/ZCohomology/Groups/RP2wedgeS1.agda
> +-- genS¹ : coHom 1 S¹
commented code

2022-09-19 13:01 UTC, mortberg commented on Cubical/ZCohomology/Groups/RP2wedgeS1.agda
> +-- proofGenS¹ : Iso.fun (fst H¹-S¹≅ℤ) genS¹ ≡ 1
same

2022-09-19 13:01 UTC, mortberg commented on Cubical/ZCohomology/Groups/RP2wedgeS1.agda
> +-- Copying x this way is clearly cheating too !
confusing comment

2022-09-19 14:02 UTC, merged