The FreeCommAlgebra on a coproduct of types
agda/cubical pull request #925
Opened 2022-09-02 19:47 UTC by felixwellen

This PR is about proving the relation
```
R[coproduct I J] = R[I][J]
```
where ```I``` and ```J``` are types which function as index-types for the variables in the generalized polynomial-rings ```R[I]``` and ```R[I][J]```. This can be used to show that 
```
R[Fin n][Fin m] = R[Fin (n+m)]
```
which are the standard multivariate polynomials in n,m and n+m variables.

2022-09-13 20:00 UTC, MatthiasHu requested changes
Great stuff! :-)
Here are some comments.

2022-09-13 20:44 UTC, felixwellen commented on Cubical/Algebra/CommAlgebra/Properties.agda
> +      baseChange (compRingHom g f) A ∎
I realized, I should remove this part - it is not needed by the PR and too slow to type check.

2022-09-13 20:52 UTC, felixwellen commented on Cubical/Algebra/CommAlgebra/FreeCommAlgebra/Properties.agda
> +  → f ≡ inducedHom A φ
Yes!

2022-09-13 20:53 UTC, felixwellen commented on Cubical/Algebra/CommAlgebra/FreeCommAlgebra/Properties.agda
>  homMapPath : {R : CommRing ℓ} {I : Type ℓ'} (A : CommAlgebra R (ℓ-max ℓ ℓ'))
Sure...

2022-09-13 21:11 UTC, felixwellen commented on Cubical/Algebra/CommAlgebra/FreeCommAlgebra/Properties.agda
> +           → (x : ⟨ R [ I ] ⟩) → fst f x ≡ fst g x
Nice!

2022-09-14 13:35 UTC, MatthiasHu approved these changes
This can be merged now imo!

2022-09-14 13:54 UTC, merged