Mayer-Vietoris
agda/cubical pull request #954
Opened 2022-11-21 13:02 UTC by aljungstrom

This PR contains the Mayer-Vietoris sequence for cohomology with arbitrary coefficients. Basically directly copied from the ZCohomology version.

2022-12-02 11:12 UTC, felixwellen commented
Do you know that `Cubical.Cohomology.EilenbergMacLane.MayerVietoris` stops to type-check (with unsolved metas) when you remove `--experimental-lossy-unification`?

2022-12-07 12:18 UTC, aljungstrom commented
Ugh, yeah, I hadn't tried it for this version, but for the ZCohomology version I had the same problem. Didn't remember the unsolved metas, but I think type-checking is too slow even when you spell them out. My guess is that Agda is unfolding the definition of the cohomology group structure every time you try to define a homomorphism of cohomology groups.

2022-12-07 14:42 UTC, felixwellen commented
I see. I don't know if anything bad can come from this.
Do you play around with "abstract" in situations like these?
For me, sometimes lossy-unification does it and sometimes abstract. In situations where both work, I prefer abstract, since that seems more controllable to me and it will have better support in the future (e.g. unfolding if you want to).
In case this is unclear: I'm not complaining and I have no idea if lossy-unifying things to something not really unique is bad.

2023-07-10 14:11 UTC, felixwellen commented
We could just merge that, if you change "--experimental-lossy-unification" to "--lossy-unification" - it still checks on current master.

2023-09-12 13:38 UTC, mortberg commented
> We could just merge that, if you change "--experimental-lossy-unification" to "--lossy-unification" - it still checks on current master.

Is this the only change needed to merge the PR?

2023-09-12 13:47 UTC, mortberg requested changes

2023-09-12 13:47 UTC, mortberg commented on Cubical/Cohomology/EilenbergMacLane/MayerVietoris.agda
> +{-# OPTIONS --safe --experimental-lossy-unification #-}
```suggestion
{-# OPTIONS --safe --lossy-unification #-}
```

2023-09-12 13:47 UTC, mortberg commented
> Last time I checked it was

I fixed it. Looks like many files still have `experimental` in them though...

2023-09-12 13:49 UTC, felixwellen commented
> > Last time I checked it was
> 
> I fixed it. Looks like many files in the library still have `experimental` in them though...

No. Did you look at the version this PR is based on?

2023-09-12 13:50 UTC, mortberg commented
> > > Last time I checked it was
> > 
> > 
> > I fixed it. Looks like many files in the library still have `experimental` in them though...
> 
> No. Did you look at the version this PR is based on?

Oh yeah, so it will be fine once we merge?

2023-09-12 13:51 UTC, felixwellen commented
Yes

2023-09-12 13:52 UTC, mortberg commented
> Yes

Great! I guess I've been too busy with other things for so long that I've forgotten how git works hehe

2023-09-12 13:52 UTC, mortberg approved these changes
With my fix let's merge this once the CI is happy

2023-09-12 13:53 UTC, felixwellen commented
It shouldn't be, because the CI will use an old version of agda ;-)

2023-09-12 13:53 UTC, felixwellen commented
If we want the CI to be happy, we will need to rebase onto master/merge master.

2023-09-12 13:59 UTC, felixwellen commented
Ok, I guess that means I have a wrong idea about what the CI actually does.

2023-09-12 14:02 UTC, mortberg commented
@felixwellen do you want to merge?

2023-09-12 14:05 UTC, felixwellen commented
I don't get why it didn't fail, but let's just merge it - I have time to fix things, if it fails.

2023-09-12 14:07 UTC, mortberg commented
> I don't get why it didn't fail, but let's just merge it - I have time to fix things, if it fails.

I guess the changes are compatible with the state of master and the CI has confirmed that it doesn't fail after merging?

2023-09-12 14:11 UTC, merged