Reduced cohomology+Eilenberg-Steenrod axioms
agda/cubical pull request #955
Opened 2022-11-21 17:02 UTC by aljungstrom

This PR contains:

1. Reduced cohomology with arbitrary group coefficients
2. A proof that this theory satisfies the Eilenberg-Steenrod axioms

2022-12-06 14:42 UTC, aljungstrom commented
> I think the definition of `coHomTheory` should also have fields `Hmap_id` and `Hmap_const`, right? Perhaps you want to add them and their proofs for ordinary cohomology in this PR also?

Wups! Thanks for pointing this out. I'll fix it in a separate PR as soon as Anders merges this one (and the Gysin one since it depends on this one).

2023-07-10 14:26 UTC, felixwellen commented
Same here. It still checks on current master, if you change "--experimental-lossy-unification" to "--lossy-unification".

2023-07-10 14:43 UTC, felixwellen requested changes
Great stuff - I only have organisational comments and one fix.

2023-07-10 14:43 UTC, felixwellen commented on Cubical/Cohomology/EilenbergMacLane/EilenbergSteenrod.agda
> +module _ {ℓ ℓ'} {G : AbGroup ℓ} where
Maybe this module should be called ```coHomRed``` or something like that? You use that as a suffix sometimes below...

2023-07-10 14:43 UTC, felixwellen commented on Cubical/Cohomology/EilenbergMacLane/Base.agda
> +          (rUnit refl)))))))
I think these names should be in a named module or private block, so it is clear they are not supposed to be exported.

2023-07-10 14:43 UTC, felixwellen commented on Cubical/Cohomology/EilenbergMacLane/Base.agda
> +open import Cubical.Foundations.Isomorphism
wrong block...

2023-07-10 14:43 UTC, felixwellen commented on Cubical/Cohomology/EilenbergMacLane/EilenbergSteenrod.agda
> +{-# OPTIONS --safe --experimental-lossy-unification #-}
```experimental-``` has to be removed.

2023-09-12 16:26 UTC, mortberg commented on Cubical/Cohomology/EilenbergMacLane/EilenbergSteenrod.agda
> +{-# OPTIONS --safe --experimental-lossy-unification #-}
```suggestion
{-# OPTIONS --safe --lossy-unification #-}
```

2023-09-12 16:28 UTC, mortberg commented on Cubical/Cohomology/EilenbergMacLane/EilenbergSteenrod.agda
> +{-# OPTIONS --safe --experimental-lossy-unification #-}
I fixed this

2023-09-12 16:29 UTC, mortberg commented
@aljungstrom Can you fix @felixwellen's comments and then we can merge? 

We should not forget to add the missing fields that @rwbarton pointed out as well

2023-09-16 08:01 UTC, mortberg commented
Merging this now. 

@aljungstrom please make a new PR adding the two missing fields from `coHomTheory` (functoriality for `Hmap`) and necessary proofs for the cohomology theories we have

2023-09-16 08:01 UTC, merged